### ISSUE TITLE
Merging efforts

### ISSUE THREAD

**Issue by andreaferretti** [jlp765/seqmath#1]
Hi, I am the author of [linalg](https://github.com/unicredit/linear-algebra), a library that _also_ aims to get something equivalent to Numpy for Nim. My efforts so far have been in binding linear algebra operations from BLAS backends (and cuBLAS as well, so it will run on the GPU!). Also, for my use case, I have concentrated on the case where dimensions are known at compile time, and I have accordingly used `static[T]` parameters to guarantee that dimensions are matched at compile time.

I now plan to add support for dynamically sized vectors and matrices, which essentially would be just seqs. I would also like to add support for element-wise operations.

I see that you have already implemented a lot of element-wise operations. Would you like to merge the efforts and contribute to a single package?

**Comment by jlp765** [comment]
Excellent.  Feel free to merge either way, but since you're working on it and I've effectively, stopped, then feel free to take over what I have done.

One question is whether it will be too big in one module, and be better split into multiple modules anyway, but as related portions of the math spectrum.  Just something to bear in mind as you proceed.
Either way, if it is unified in approach, the consistency will be a bonus.

If you merge my stuff into the linalg, then I can remove the seqmath library at some point  (I'm not that precious about it :-) )

**Comment by jlp765** [comment]
One thing I didn't work out, was lifting procs like `arctan2()`, `hypot()`, `pow()` where they take two parameters.  
The `liftScalarProc()` template can only handle single parameter procs.

**Comment by andreaferretti** [comment]
Thank you! I will first add the part about dynamic size, and then incorporate your work :-)

**Comment by andreaferretti** [comment]
I have added support for universal functions [here](https://github.com/unicredit/linear-algebra#universal-functions). I did not follow your exact approach, because the datatypes in linalg are slightly different, nor did I cover everything in seqmath, but it is a start :-)
